export const FEET_LIST_PRODUCTS = "FEET_LIST_PRODUCTS";
export const FEET_LIST_PRODUCTS_SUCCESS = "FEET_LIST_PRODUCTS_SUCCESS";
export const FEET_LIST_PRODUCTS_ERROR = "FEET_LIST_PRODUCTS_ERROR";
export const CHANGE_LOADING_STATUS = "CHANGE_LOADING_STATUS";
export const CHANGE_LOADING_STATUS_FALSE = "CHANGE_LOADING_STATUS_FALSE";
export const FEET_SINGLE_PRODUCTS = "FEET_SINGLE_PRODUCTS";
export const FEET_SINGLE_PRODUCTS_SUCCESS = "FEET_SINGLE_PRODUCTS_SUCCESS";

